FROM frolvlad/alpine-oraclejdk8
COPY com.commsen.liferay.builtwith.rest.jar /app/com.commsen.liferay.builtwith.rest.jar
WORKDIR /app
ENTRYPOINT ["java","-jar","/app/com.commsen.liferay.builtwith.rest.jar"]